### PR TITLE
Adds the entire data as a json to be used for databases

### PR DESCRIPTION
**Pull request by mugabits**
This file can be used as a import to a nosql database either mongodb or cassandra.

### CODE REVIEW

**Comment by mugabits** [comment]
The commit fdec93f fixes issue #16, but it can merged through a new pull request . I can create a new pull request for issue #16  once this one is merged.

**Comment by mugabits** [comment]
I imported the raw data into a mongodb and then export it as budget.json for anyone else to use. 

@maurop123 : Waiting on your approval before merging this, and please let me know if there is any questions on how to import/export data using mongodb.

**Comment by maurop123** [comment]
There have been some changes to the index. I'll be pulling this down to merge manually and then committing tmrw.

Thx for making the data jsons. Will add them to the repo tmrw. The site currently is static and not using mongodb or server side script to even connect with on. Of course, it can read the static json instead, but then that's no difference from the csvs. 

Soon, we may want to connect to the open portal API instead. @mugab686 do you have a reason why we should store and call the data from mongo?

**Comment by mugabits** [comment]
Using a database is faster and less complex than using a REST API. Also, when the API changes, it won't directly affect this application, and we can filter those changes with an abstraction layer. 

I picked mongo because I think it is simpler and flexible in case changes are introduced to the schema. Also, we can add easily add other fields with a noSQL instance. 

As far as connecting to a mongodb, we can create a simple script that does that in any prog language -ruby, python, node. AWS and meteor integrate well with mongo as well.

**Comment by mugabits** [comment]
Closing the pull request since the project structure changed, and now is a meteor app. I may send another PR in the near future, but more related to new meteor app.

**Pull request closed without merging**
